@extends('Administrative::layouts.public')
@section('title', $procedure->name)
@section('content')
<div class="mx-auto max-w-4xl px-4 py-10 sm:px-6"><a href="{{ route('administrative.public.index') }}" class="text-sm font-semibold text-indigo-600">← Danh sách thủ tục</a><div class="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="text-sm font-semibold text-indigo-600">{{ $procedure->code }}</div><h1 class="mt-2 text-2xl font-bold">{{ $procedure->name }}</h1>@if($procedure->description)<p class="mt-3 text-slate-600">{{ $procedure->description }}</p>@endif
@if($procedure->instructions)<section class="mt-7"><h2 class="font-semibold">Hướng dẫn thực hiện</h2><div class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $procedure->instructions }}</div></section>@endif
<section class="mt-7"><h2 class="font-semibold">Giấy tờ cần chuẩn bị</h2>@if($procedure->required_documents)<ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">@foreach($procedure->required_documents as $item)<li>{{ $item }}</li>@endforeach</ul>@else<p class="mt-2 text-sm text-slate-500">Chi tiết được thể hiện trong biểu mẫu.</p>@endif</section>
<div class="mt-7 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Cho phép tối đa <strong>{{ $procedure->max_files }} file</strong>, mỗi file không quá <strong>{{ number_format($procedure->max_file_size_kb / 1024, 0) }} MB</strong>. Định dạng: {{ strtoupper(implode(', ', $procedure->allowed_extensions ?? [])) }}.</div>
<div class="mt-7 flex flex-col gap-3 sm:flex-row">@if($procedure->template_path)<a href="{{ route('administrative.public.template.download', $procedure) }}" class="inline-flex justify-center rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700">Tải biểu mẫu</a>@endif<a href="{{ route('administrative.public.submit', $procedure) }}" class="inline-flex justify-center rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Nộp hồ sơ</a></div></div></div>
@endsection
