@extends('Administrative::layouts.public')
@section('title', 'Nộp hồ sơ thành công')
@section('robots', 'noindex,nofollow,noarchive')
@section('content')
<div class="mx-auto max-w-3xl px-4 py-12 sm:px-6"><div class="rounded-2xl border border-green-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex h-12 w-12 items-center justify-center rounded-full bg-green-100 text-2xl text-green-700">✓</div><h1 class="mt-5 text-2xl font-bold">Nộp hồ sơ thành công</h1><p class="mt-2 text-slate-600">Hãy lưu lại cả mã hồ sơ và mã tra cứu. Mã tra cứu chỉ được hiển thị tại biên nhận này.</p>
<dl class="mt-6 divide-y divide-slate-200 rounded-xl border border-slate-200">@foreach(['Mã hồ sơ'=>$submission->submission_code,'Mã tra cứu bí mật'=>$lookupToken,'Thủ tục'=>$submission->procedure->name,'Ngày nộp'=>$submission->submitted_at->format('d/m/Y H:i'),'Trạng thái'=>'Chờ duyệt'] as $label=>$value)<div class="grid gap-1 px-4 py-3 sm:grid-cols-3"><dt class="text-sm text-slate-500">{{ $label }}</dt><dd class="break-all text-sm font-semibold text-slate-900 sm:col-span-2">{{ $value ?: 'Không còn hiển thị' }}</dd></div>@endforeach</dl>
@if($submission->wants_email_receipt)<div class="mt-6 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-800">Biên nhận đã được xếp hàng gửi tới {{ $submission->email }}.</div>@endif
<div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Không chia sẻ mã tra cứu cho người khác. Nếu đóng phiên trình duyệt, hệ thống không thể hiển thị lại mã bí mật này.</div><div class="mt-6 flex flex-col gap-3 sm:flex-row"><a href="{{ route('administrative.public.receipt.download', request()->route('receipt')) }}" class="inline-flex justify-center rounded-xl border border-indigo-300 bg-white px-5 py-3 text-sm font-semibold text-indigo-700">Tải biên nhận PDF</a><a href="{{ route('administrative.public.index') }}" class="inline-flex justify-center rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Về danh sách thủ tục</a></div></div></div>
@endsection
