<form wire:submit="submit" class="space-y-6">
    <div><a href="{{ route('administrative.public.show', $procedure) }}" class="text-sm font-semibold text-indigo-600">← Quay lại thủ tục</a><h1 class="mt-4 text-2xl font-bold">Nộp hồ sơ trực tuyến</h1><p class="mt-2 text-slate-600">{{ $procedure->name }}</p></div>
    @error('form')<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $message }}</div>@enderror
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Thông tin người nộp</h2><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2">
        <div><label class="text-sm font-medium text-gray-700">Họ tên người nộp <span class="text-red-600">*</span></label><input wire:model="applicant_name" type="text" autocomplete="name" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error('applicant_name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium text-gray-700">Số điện thoại <span class="text-red-600">*</span></label><input wire:model="phone" type="tel" autocomplete="tel" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error('phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Email</label><input wire:model="email" type="email" autocomplete="email" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error('email')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror<label class="mt-3 flex items-start gap-3 rounded-xl bg-slate-50 p-3"><input wire:model="wants_email_receipt" type="checkbox" class="mt-1"><span class="text-sm text-slate-700">Gửi biên nhận và mã tra cứu đến email này</span></label></div>
    </div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Thông tin học sinh</h2><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2">
        @foreach(['student_name'=>'Họ tên học sinh *','student_code'=>'Mã học sinh','current_class'=>'Lớp hiện tại','academic_year'=>'Năm học'] as $field=>$label)<div><label class="text-sm font-medium text-gray-700">{{ $label }}</label><input wire:model="{{ $field }}" type="text" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error($field)<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
        <div><label class="text-sm font-medium text-gray-700">Ngày sinh</label><input wire:model="date_of_birth" type="date" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error('date_of_birth')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium text-gray-700">Quan hệ với học sinh</label><select wire:model.live="relationship" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"><option value="">Chọn quan hệ</option><option value="father">Cha</option><option value="mother">Mẹ</option><option value="guardian">Người giám hộ</option><option value="student">Học sinh tự nộp</option><option value="other">Khác</option></select>@error('relationship')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        @if($relationship === 'other')<div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Quan hệ khác</label><input wire:model="relationship_other" type="text" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('relationship_other')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endif
    </div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">File hồ sơ</h2><p class="mt-1 text-sm text-slate-500">Tối đa {{ $procedure->max_files }} file, {{ number_format($procedure->max_file_size_kb / 1024, 0) }} MB/file. {{ strtoupper(implode(', ', $procedure->allowed_extensions ?? [])) }}.</p><input wire:model="files" type="file" multiple class="mt-4 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('files')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror @error('files.*')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror<div wire:loading wire:target="files" class="mt-2 text-sm text-indigo-600">Đang tải file lên...</div>@if($files)<ul class="mt-3 space-y-1 text-sm text-slate-600">@foreach($files as $file)<li>{{ $file->getClientOriginalName() }}</li>@endforeach</ul>@endif</section>
    <label class="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-4"><input wire:model="privacy_consent" type="checkbox" class="mt-1"><span class="text-sm text-slate-700">Tôi xác nhận thông tin là chính xác và đồng ý để nhà trường xử lý dữ liệu nhằm giải quyết hồ sơ này.</span></label>@error('privacy_consent')<p class="text-sm text-red-600">{{ $message }}</p>@enderror
    <div class="flex justify-end"><button type="submit" wire:loading.attr="disabled" class="inline-flex min-w-40 justify-center rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 disabled:opacity-60"><span wire:loading.remove wire:target="submit">Nộp hồ sơ</span><span wire:loading wire:target="submit">Đang xử lý...</span></button></div>
</form>
