@php
    $status = $submission->status->value;
    $statusLabel = ['pending' => 'Chờ duyệt', 'need_supplement' => 'Yêu cầu bổ sung', 'approved' => 'Đã duyệt', 'rejected' => 'Bị từ chối'][$status] ?? $status;
@endphp
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div><a href="{{ route('admin.administrative.submissions.index') }}" class="text-sm font-semibold text-indigo-600">← Danh sách hồ sơ</a><h1 class="mt-2 text-2xl font-bold text-gray-900">{{ $submission->submission_code }}</h1><p class="mt-1 text-sm text-gray-500">{{ $submission->procedure->name }}</p></div>
        <div class="flex flex-wrap gap-3">
            @if($submission->status === $pendingStatus && auth('admin')->user()?->can('administrative.submission.edit'))
                <button wire:click="$set('showSupplement', true)" class="rounded-xl bg-amber-600 px-5 py-3 text-sm font-semibold text-white">Yêu cầu bổ sung</button>
                <button wire:click="$set('showReject', true)" class="rounded-xl bg-red-600 px-5 py-3 text-sm font-semibold text-white">Từ chối</button>
                <button wire:click="$set('showApprove', true)" class="rounded-xl bg-green-600 px-5 py-3 text-sm font-semibold text-white">Phê duyệt</button>
            @endif
        </div>
    </div>
    @error('processing')<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $message }}</div>@enderror
    @error('email')<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $message }}</div>@enderror

    <div class="grid gap-6 lg:grid-cols-3">
        <div class="space-y-6 lg:col-span-2">
            <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Thông tin hồ sơ</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">
                @foreach(['Trạng thái'=>$statusLabel,'Người nộp'=>$submission->applicant_name,'Số điện thoại'=>$submission->phone,'Email'=>$submission->email ?: '-','Học sinh'=>$submission->student_name,'Mã học sinh'=>$submission->student_code ?: '-','Ngày sinh'=>$submission->date_of_birth?->format('d/m/Y') ?? '-','Lớp / Năm học'=>trim(($submission->current_class ?: '-').' / '.($submission->academic_year ?: '-')),'Quan hệ'=>$submission->relationship ?: '-','Ngày nộp'=>$submission->submitted_at->format('d/m/Y H:i')] as $label=>$value)<div><dt class="text-xs uppercase text-gray-500">{{ $label }}</dt><dd class="mt-1 font-medium text-gray-900">{{ $value }}</dd></div>@endforeach
            </dl></section>
            <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">File đính kèm</h2><div class="mt-4 divide-y divide-gray-200 rounded-xl border border-gray-200">
                @forelse($submission->files as $file)<div class="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="text-sm font-medium">{{ $file->original_name }}</div><div class="text-xs text-gray-500">{{ strtoupper($file->file_type->value) }} · {{ $file->mime_type }} · {{ number_format($file->size/1024, 0) }} KB</div></div><a href="{{ route('admin.administrative.submissions.files.download', [$submission->id,$file->id]) }}" class="text-sm font-semibold text-indigo-600">Tải file</a></div>@empty<div class="p-5 text-sm text-gray-500">Không có file đính kèm.</div>@endforelse
            </div></section>
        </div>
        <aside class="space-y-6">
            <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Thông tin xử lý</h2><dl class="mt-4 space-y-4 text-sm"><div><dt class="text-gray-500">Người xử lý</dt><dd class="font-medium">{{ $submission->processor?->name ?? '-' }}</dd></div><div><dt class="text-gray-500">Thời gian</dt><dd class="font-medium">{{ $submission->processed_at?->format('d/m/Y H:i') ?? '-' }}</dd></div><div><dt class="text-gray-500">Số lần bổ sung</dt><dd class="font-medium">{{ $submission->revision_count }}</dd></div>@if($submission->response)<div><dt class="text-gray-500">Phản hồi</dt><dd class="whitespace-pre-line font-medium">{{ $submission->response }}</dd></div>@endif @if($submission->supplement_reason)<div><dt class="text-amber-600">Yêu cầu bổ sung</dt><dd class="whitespace-pre-line font-medium text-amber-800">{{ $submission->supplement_reason }}</dd></div>@endif @if($submission->rejection_reason)<div><dt class="text-red-500">Lý do từ chối</dt><dd class="whitespace-pre-line font-medium text-red-700">{{ $submission->rejection_reason }}</dd></div>@endif</dl></section>
            <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Lịch sử</h2><ol class="mt-4 space-y-4">@foreach($submission->statusHistories as $history)<li class="border-l-2 border-indigo-200 pl-4"><div class="text-sm font-medium">{{ $history->action->value }}</div><div class="text-xs text-gray-500">{{ $history->created_at->format('d/m/Y H:i') }} · {{ $history->actorAdmin?->name ?? ucfirst($history->actor_type->value) }}</div>@if($history->reason)<p class="mt-1 text-xs text-red-600">{{ $history->reason }}</p>@endif</li>@endforeach</ol></section>
        </aside>
    </div>

    @if($showApprove)<section class="rounded-2xl border border-green-200 bg-green-50 p-5"><h2 class="font-semibold text-green-900">Xác nhận phê duyệt</h2><textarea wire:model="response" rows="4" placeholder="Phản hồi cho người nộp (không bắt buộc)" class="mt-4 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm"></textarea>@error('response')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror<div class="mt-4 flex gap-3"><button wire:click="approve" wire:loading.attr="disabled" class="rounded-xl bg-green-600 px-5 py-3 text-sm font-semibold text-white">Xác nhận duyệt</button><button wire:click="$set('showApprove', false)" class="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold">Hủy</button></div></section>@endif
    @if($showSupplement)<section class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold text-amber-900">Yêu cầu bổ sung</h2><textarea wire:model="supplement_reason" rows="4" placeholder="Nêu rõ giấy tờ hoặc thông tin cần bổ sung" class="mt-4 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm"></textarea>@error('supplement_reason')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror<textarea wire:model="response" rows="3" placeholder="Phản hồi bổ sung (không bắt buộc)" class="mt-4 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm"></textarea><div class="mt-4 flex gap-3"><button wire:click="requestSupplement" wire:loading.attr="disabled" class="rounded-xl bg-amber-600 px-5 py-3 text-sm font-semibold text-white">Xác nhận yêu cầu</button><button wire:click="$set('showSupplement', false)" class="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold">Hủy</button></div></section>@endif
    @if($showReject)<section class="rounded-2xl border border-red-200 bg-red-50 p-5"><h2 class="font-semibold text-red-900">Từ chối hồ sơ</h2><div class="mt-4 grid gap-4"><select wire:model="reason_code" class="rounded-xl border border-gray-300 px-4 py-3 text-sm"><option value="">Chọn nhóm lý do</option>@foreach(['wrong_form'=>'Sai biểu mẫu','missing_signature'=>'Thiếu chữ ký','missing_documents'=>'Thiếu giấy tờ','unreadable_file'=>'File không đọc được','mismatched_information'=>'Thông tin không khớp','ineligible'=>'Không đủ điều kiện','other'=>'Lý do khác'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>@error('reason_code')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<textarea wire:model="rejection_reason" rows="4" placeholder="Lý do chi tiết, tối thiểu 10 ký tự" class="rounded-xl border border-gray-300 px-4 py-3 text-sm"></textarea>@error('rejection_reason')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<textarea wire:model="response" rows="3" placeholder="Phản hồi bổ sung" class="rounded-xl border border-gray-300 px-4 py-3 text-sm"></textarea></div><div class="mt-4 flex gap-3"><button wire:click="reject" wire:loading.attr="disabled" class="rounded-xl bg-red-600 px-5 py-3 text-sm font-semibold text-white">Xác nhận từ chối</button><button wire:click="$set('showReject', false)" class="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold">Hủy</button></div></section>@endif
</div>
