<form wire:submit="save" class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold text-gray-900">{{ $procedureId ? 'Chỉnh sửa' : 'Thêm' }} thủ tục</h1><p class="mt-1 text-sm text-gray-500">Cấu hình nội dung, biểu mẫu và quy tắc file.</p></div><a href="{{ route('admin.administrative.procedures.index') }}" class="inline-flex justify-center rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold text-gray-700">Quay lại</a></div>

    <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Thông tin chung</h2><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2">
        @foreach(['code'=>'Mã thủ tục','name'=>'Tên thủ tục','slug'=>'Slug'] as $field=>$label)<div class="{{ $field === 'name' ? 'md:col-span-2' : '' }}"><label class="text-sm font-medium text-gray-700">{{ $label }}</label><input wire:model.live="{{ $field }}" type="text" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error($field)<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
        <div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Mô tả</label><textarea wire:model="description" rows="3" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"></textarea>@error('description')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Hướng dẫn</label><textarea wire:model="instructions" rows="6" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"></textarea>@error('instructions')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Giấy tờ cần nộp (mỗi dòng một mục)</label><textarea wire:model="required_documents_text" rows="5" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"></textarea>@error('required_documents_text')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    </div></div>

    <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Biểu mẫu và file hồ sơ</h2><div class="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2">
        <div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Biểu mẫu (PDF, DOC, DOCX; tối đa 10 MB)</label><input wire:model="template" type="file" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@if($currentTemplateName)<p class="mt-2 text-sm text-gray-500">Hiện tại: <a class="font-medium text-indigo-600 hover:text-indigo-500" href="{{ route('admin.administrative.procedures.template.download', $procedureId) }}">{{ $currentTemplateName }}</a></p><label class="mt-2 inline-flex items-center gap-2 text-sm text-red-600"><input type="checkbox" wire:model="removeTemplate"> Xóa biểu mẫu hiện tại</label>@endif @error('template')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="md:col-span-2"><span class="text-sm font-medium text-gray-700">Định dạng hồ sơ cho phép</span><div class="mt-2 flex flex-wrap gap-4">@foreach(['pdf','doc','docx','jpg','jpeg','png'] as $ext)<label class="inline-flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" wire:model="allowed_extensions" value="{{ $ext }}"> {{ strtoupper($ext) }}</label>@endforeach</div>@error('allowed_extensions')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium text-gray-700">Dung lượng tối đa (KB)</label><input wire:model="max_file_size_kb" type="number" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('max_file_size_kb')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium text-gray-700">Số file tối đa</label><input wire:model="max_files" type="number" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('max_files')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium text-gray-700">Thứ tự</label><input wire:model="sort_order" type="number" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('sort_order')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <label class="flex items-center gap-3 self-end rounded-xl border border-gray-200 px-4 py-3"><input type="checkbox" wire:model="is_active"><span class="text-sm font-medium text-gray-700">Đang hoạt động</span></label>
    </div></div>
    <div class="flex justify-end"><button type="submit" wire:loading.attr="disabled" class="inline-flex items-center justify-center rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 disabled:opacity-60"><span wire:loading.remove wire:target="save">Lưu thủ tục</span><span wire:loading wire:target="save">Đang lưu...</span></button></div>
</form>
